
# Conectar ao Postgres (pgAdmin)
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/TodoList
spring.datasource.username=postgres
spring.datasource.password=postgres
# Configuração para carregar dados iniciais de um arquivo SQL
#spring.sql.init.data-locations=classpath:import.sql
# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always

#config do actuator 
#spring.boot.admin.client.url=http://localhost:8081
#management.endpoint.health.show-details = always
#management.endpoints.web.exposure.include=*
#management.info.env.enabled=true 
