INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE) VALUES ('MERO','MEROTESTE',FALSE,1)
INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE) VALUES ('mero1','MEROTESTE',FALSE,1)
-- INSERT INTO Usuarios (NOME, EMAIL,SENHA  ) VALUES ('dragon','dragon@gmail.com','12345678')