
INSERT INTO Usuarios (NOME, EMAIL,SENHA  ) VALUES ('dRagon','dragon@gmail.com','12345678')
INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE,USER_ID) VALUES ('MERO','MEROTESTE',FALSE,1,1)
INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE,USER_ID) VALUES ('mero1','MEROTESTE',FALSE,1,1)