
INSERT INTO Usuarios (NOME, EMAIL,SENHA, ROLE  ) VALUES ('dRagon','dragon@gmail.com','12345678',0)
INSERT INTO Usuarios (NOME, EMAIL,SENHA,ROLE  ) VALUES ('teste','meroteste','$2a$10$AKv6cCleU.tYMvEx.SqwPufpwVB2Rzy2a99/BJxFE3Eo9hGjVcjn2',0)
INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE,USER_ID) VALUES ('MERO','MEROTESTE',FALSE,1,1)
INSERT INTO TODOS (NOME,DESCRICAO,REALIZADO,PRIORIDADE,USER_ID) VALUES ('mero1','MEROTESTE',FALSE,1,1)